<?php 
namespace Apps\Form;

use Cygnite\FormBuilder\Form;
use Cygnite\Foundation\Application;
use Cygnite\Common\UrlManager\Url;

/**
* Sample Form using Cygnite Form Builder
* This file generated by Cygnite CLI Generator.
* You may alter the code to fit your needs
*/

class BreedForm extends Form
{
    //set model object
    private $model;

    public $errors;

    private $segment;

    // We will set action url
    public $action = 'add';

    public function __construct($object = null, $segment = null)
    {
        // your model object
        $this->model = $object;
        $this->segment = $segment;
    }

    /**
    * Set validator used for displaying validation
    * errors below each form elements
    *
    * @param $validator
    * @return $this
    */
    public function setValidator($validator)
    {
        $this->validator = $validator;

        return $this;
    }

    /**
     *  Build form and return object
     * @return BreedForm
     */
    public function buildForm()
    {
        $id = (isset($this->model->id)) ? $this->model->id : '';

        // Below code is to display validation errors below the input box
        if (is_object($this->validator)) {
            // Set your custom errors
            //$this->validator->setCustomError('column.error', 'Your Custom Error Message');
        }

        $this->open("BreedController", array(
        "method" => "post", "id"     => "uniform", "role"   => "form", "action" => Url::sitePath("breed/$this->action/$id/"),
        "style" => "width:500px;margin-top:35px;float:left;" )
        )		->addElement("label", "Name", array("class" => "col-sm-2 control-label","style" => "width:100%;"))
		->addElement("text", "name", array("value" => (isset($this->model->name)) ? $this->model->name : "", "class" => "form-control"))
		->addElement("label", "Descr", array("class" => "col-sm-2 control-label","style" => "width:100%;"))
		->addElement("text", "descr", array("value" => (isset($this->model->descr)) ? $this->model->descr : "", "class" => "form-control"))
		->addElement("label", "Date", array("class" => "col-sm-2 control-label","style" => "width:100%;"))
		->addElement("text", "date", array("value" => (isset($this->model->date)) ? $this->model->date : "", "class" => "form-control"))
		->addElement("submit", "btnSubmit", array("value" => "Save", "class" => "btn btn-primary", "style" => "margin-top:15px;" ))
		->close()
		->createForm();



        return $this;
    }

    /**
     * Render form
     * @return type
     */
    public function render()
    {
        return $this->buildForm()->getForm();
    }
}